# Generated by Django 4.2.7 on 2025-06-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coloranalysisstats_processingjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Local uploaded image', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='processingjob',
            name='job_type',
            field=models.CharField(choices=[('color_analysis', 'Renk Analizi'), ('visual_features', 'Görsel Özellik Çıkarma'), ('text_embedding', 'Metin Embedding'), ('standard_processing', 'Standart İşleme')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_front_url',
            field=models.URLField(blank=True, help_text='Front image URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL'),
        ),
    ]
