# Generated by Django 4.2.7 on 2025-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_store_city_store_country_store_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
